#!/bin/sh
ip link set dev enp0s8 up
ip addr add 10.0.0.2/24 dev enp0s8 
route add -net 10.0.0.0 netmask 255.255.255.0 gw 10.0.0.2

ip link set dev enp0s9 up
ip addr add 10.0.1.2/24 dev enp0s9 
route add -net 10.0.1.0 netmask 255.255.255.0 gw 10.0.1.2
